#!/usr/bin/perl -w

use strict;
use File::Temp qw/ tempfile tempdir /;
use Cwd;

# delete tmp dirs on exit?
my $CLEANUP = 0;

my @tests = (
    { "name" => "test1",
      "unreduced" => "file1.c",
      "test_script" => "test1.sh",
      "expected" => "test1_expected.c",
    },
    { "name" => "test2",
      "unreduced" => "file1.c",
      "test_script" => "test2.sh",
      "expected" => "test2_expected.c",
    },
    { "name" => "test3",
      "unreduced" => "file1.c",
      "test_script" => "test3.sh",
      "expected" => "test3_expected.c",
    },
    { "name" => "test4",
      "unreduced" => "file2.c",
      "test_script" => "test4.sh",
      "expected" => "test4_expected.c",
    },
    { "name" => "test5",
      "unreduced" => "file2.c",
      "test_script" => "test5.sh",
      "expected" => "test5_expected.c",
    },
    { "name" => "test6",
      "unreduced" => "file2.c",
      "test_script" => "test6.sh",
      "expected" => "test6_expected.c",
    },
    );

foreach my $tref (@tests) {
    my %test = %{$tref};

    my $name = $test{"name"};
    my $unreduced = $test{"unreduced"};
    my $test_script = $test{"test_script"};
    my $expected = $test{"expected"};
    die unless (defined ($name) &&
		defined ($unreduced) &&
		defined ($test_script) &&
		defined ($expected));

    my $test_dir = getcwd();
    my $temp_dir = tempdir( "tmp_${name}_XXXXX", 
		       DIR => $test_dir,
		       CLEANUP => $CLEANUP );

    chdir $temp_dir or die;

    system "cp ../$unreduced small.c";
    system "creduce ../${test_script} small.c";
    
    chdir $test_dir or die;
}
