#!/usr/bin/perl -w

use strict;
use File::Temp qw/ tempfile tempdir /;
use Cwd;

# delete tmp dirs?
my $CLEANUP = 0;

my @tests = (
    { "name" => "test1",
      "unreduced" => "file1.c",
      "test_script" => "test1.sh",
      "expected" => "test1_expected.c",
    }
    );

foreach my $tref (@tests) {
    my %test = %{$tref};

    my $name = $test{"name"};
    my $unreduced = $test{"unreduced"};
    my $test_script = $test{"test_script"};
    my $expected = $test{"expected"};
    die unless (defined ($name) &&
		defined ($unreduced) &&
		defined ($test_script) &&
		defined ($expected));

    my $test_dir = getcwd();
    my $temp_dir = tempdir( "${name}_XXXXX", 
		       DIR => $test_dir,
		       CLEANUP => $CLEANUP );

    print "$temp_dir\n";
    exit 0;

    chdir $temp_dir or die;

    system "cp ../$unreduced small.c";
    system "c_reduce ../${test_script} small.c";
    
    chdir $test_dir or die;
}
