#!/usr/bin/env bash
##
## Copyright (c) 2012, 2016 The University of Utah
## All rights reserved.
##
## This file is distributed under the University of Illinois Open Source
## License.  See the file COPYING for details.

###############################################################################

multidelta -level=0 $1 $2
multidelta -level=0 $1 $2
multidelta -level=1 $1 $2
multidelta -level=1 $1 $2
multidelta -level=2 $1 $2
multidelta -level=2 $1 $2
multidelta -level=10 $1 $2
multidelta -level=10 $1 $2
